forge "http://forge.puppetlabs.com"

mod 'puppetlabs-stdlib', '5.2.0'
mod 'puppetlabs-translate', '1.2.0'
mod 'puppetlabs-mysql', '8.1.0'

mod 'puppetlabs-concat', '5.3.0'
mod 'puppetlabs-apache', '4.1.0'

mod 'puppetlabs-inifile', '3.0.0'
